title: Use Pug with Jekyll
description: Finally. A practical way to use Pug with Jekyll.

source: src
destination: "dist"

url: http://jekyll-pug.dougie.io
livereload: true
sass:
  sass_dir: static/css

TwitterImage: /static/img/twitter-card.png
FacebookImage: /static/img/open-graph.png
